name: 'Relocation - Pull_Rakshana'

on:
  workflow_dispatch:

env:
  modulesFolder: './Modules'
  WorkloadFolderName: 'Infra_Apps'
  skipComponentGovernanceDetection: true
  branch: 'relocationpullbranch'
  commit_message: 'Automated commit'
  pull_request: 'Automated State'

jobs:
  job_pull:
    name: 'Relocation Pull'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: 'Execute shared steps'
        uses: ./.github/actions/templates/sharedSteps
        with:
          ARM_CLIENT_ID: '${{ secrets.ARM_CLIENT_ID }}'
          ARM_CLIENT_SECRET: '${{ secrets.ARM_CLIENT_SECRET }}'
          ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
          modulesFolder: '${{ env.modulesFolder }}'

      - name: 'Branch detection'
        run: |
          $oldbranchname='${{ env.branch }}'
          $branches=git branch -a
          Write-Output "1. All branches: $branches"
          foreach($branch in $branches){
            $modifiedbranch=$branch.Replace('remotes/origin/','')
            Write-Output "2. Modified branch: $modifiedbranch"
            if($modifiedbranch -match $oldbranchname+'_'){
              $emptyarray=@()
              $numberonly=$modifiedbranch.Substring($modifiedbranch.IndexOf('_')+1)
              $emptyarray+=$numberonly
            }
            else{
              $emptyarray+=0
            }
          }
          Write-Output "3. Empty array: $emptyarray"
          $latestnumber=($emptyarray | measure -Maximum).Maximum + 1
          Write-Output "4. Latest number: $latestnumber"
          $newbranchname= $oldbranchname+'_'+$latestnumber
          write-Output "5. Name of new branch: '$newbranchname'"
          Write-Output "newbranchname=$newbranchname" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: 'Initialize'
        run: |
          try{
            Write-Output "1. GitHub workspace: $env:GITHUB_WORKSPACE"
            Write-Output "2. New branch name received: '${{ env.newbranchname }}'"
            $Env:PSModulePath = $Env:PSModulePath, '${{ env.modulesFolder }}' -join [IO.Path]::PathSeparator
            Import-Module .\utilities\tools\Carmlizer\src\internal\Functions\DiscoverResources.ps1 -Force
            Import-Module .\utilities\tools\Carmlizer\src\internal\Functions\Update-FolderStructureInJson.ps1 -Force
            Import-Module .\utilities\tools\Carmlizer\src\internal\Functions\Modify-SettingFileName.ps1 -Force
            Import-Module .\utilities\tools\Carmlizer\src\Get-CARMLPull.ps1 -Force
            Import-Module .\utilities\tools\Carmlizer\src\internal\Functions\Convert-ARMToBicepParameters.ps1 -Force

            $settingfile=get-content -path \utilities\tools\Carmlizer\src\Settings.json
            $IncludeWorkloadSubscriptionId=($settingfile | ConvertFrom-Json).RelocationSettings.IncludeWorkloadSubscriptionId
            foreach($subscriptionid in $IncludeWorkloadSubscriptionId)
            {
              Get-CARMLPull -SubscriptionId $subscriptionid
              Update-FolderStructureInJson -SubscriptionId $subscriptionid
              # Script-Curation -SubscriptionId $subscriptionid
            }
            modify-settingfilename -workloadname ${{ env.WorkloadFolderName }}

            #redirect error
            $GIT_REDIRECT_STDERR = '2>&1'

            Write-Verbose "Setting git config...." -Verbose

            git config --global user.email "azuredevops@microsoft.com"
            git config --global user.name "Azure DevOps"

            git branch

            Write-Verbose "CHECK GIT STATUS..." -Verbose
            git status

            Write-Verbose "git checkout...." -Verbose
            git checkout -b ${{ env.newbranchname }}

            Write-Verbose "git pull...." -Verbose
            git pull origin ${{ env.newbranchname }}

            Write-Verbose "GIT ADD..." -Verbose
            git add "${{ env.WorkloadFolderName }}/" $env:GITHUB_WORKSPACE/utilities/tools/Carmlizer/src/"${{ env.WorkloadFolderName }}"_Settings.json

            Write-Verbose "GIT REMOVE..." -Verbose
            git rm $env:GITHUB_WORKSPACE/utilities/tools/Carmlizer/utilities/tools/Carmlizer/src/Settings.json

            Write-Verbose "Commiting the changes..." -Verbose
            git commit -m "Update from Build"

            Write-Verbose "Pushing the changes..." -Verbose
            git push origin "${{ env.newbranchname }}"

            Write-Verbose "CHECK GIT STATUS..." -Verbose
            git status
          }
          catch{
            $branchName = '${{ env.newbranchname }}'
            Import-Module "$env:GITHUB_WORKSPACE\utilities\tools\Carmlizer\src\internal\Functions\Log-Exceptions.ps1" -Force
            $scriptPath= ($MyInvocation.MyCommand).Definition
            $scriptName= "Pull-Pipeline"+"_"+([io.fileinfo]$MyInvocation.MyCommand.Definition).BaseName
            $settinglocation=(Get-ChildItem -Path "$env:GITHUB_WORKSPACE\utilities\tools\Carmlizer\src\").Name
            foreach($locationfile in $settinglocation){
              if($locationfile -match "Settings.json")
              {
                $settingfile=get-content -path "$env:GITHUB_WORKSPACE\utilities\tools\Carmlizer\src\$locationfile"
                $logPath=($settingfile | ConvertFrom-Json).RelocationSettings.LogPath
              }
            }
            $Result = ""
            if($Error.Count){ $Result = "Failed"}
            Log-Exceptions -ScriptName $scriptName -LogPath "$env:GITHUB_WORKSPACE\utilities\tools\Carmlizer\$logPath" -Exception "$($PSItem.Exception.Message)" -Result $Result -ScriptPath $scriptPath -branchName $branchName
            $LASTEXITCODE = 1
            write-host "powershell exit code" $LASTEXITCODE -BackgroundColor Red
          }
        shell: pwsh
